export const SCREEN = {
    HOME: 'HOME',
    LOGIN: 'LOGIN',
    Home: 'Home',
    REGISTRATION: 'REGISTRATION',
    NOTES: 'NOTES',
    FREQUENCY: 'FREQUENCY',
    TIME: 'TIME',
    _GRADE_REGISTRATION: '_GRADE_REGISTRATION',
    FORGOT: 'FORGOT',
} as const;